apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: universalis-bot
  labels:
    app: universalis-bot
spec:
  replicas: 5
  serviceName: universalis-bot
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: universalis-bot
  template:
    metadata:
      labels:
        app: universalis-bot
    spec:
      containers:
      - name: universalis-bot
        image: registry.digitalocean.com/nesthub/universalis_bot_development:latest
        imagePullPolicy: Always
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: bot-token
        - name: CLIENT_ID
          value: "1086389807036518441"
        - name: GUILD_ID
          value: "1084182413934088313"
        - name: CHATGPT_API
          valueFrom:
            secretKeyRef:
              name: bot-secrets
              key: chatgpt-token
        - name: FEEDBACK_CHANNEL
          value: "1086390713782112286"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bot-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: universalis-bot